# Generated by Django 4.2.23 on 2025-09-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('ideal_temperature', models.FloatField()),
                ('sensor_wake_time', models.IntegerField()),
                ('sensor_sleep_time', models.IntegerField()),
            ],
            options={
                'permissions': [('change_temperature', 'User can change ideal temperature'), ('change_wakesleep', 'User can change Wake and Sleep time of device'), ('assign_device', 'Can assign a device to a room'), ('view_auditlog', 'Can view room audit logs'), ('manage_users', 'Can manage users and roles')],
            },
        ),
    ]
