# Generated by Django 4.2.23 on 2025-09-03 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('change_temperature', 'User can change ideal temperature'), ('change_wakesleep', 'User can change Wake and Sleep time of device'), ('assign_device', 'Can assign a device to a room'), ('view_auditlog', 'Can view room audit logs')]},
        ),
    ]
