# Generated by Django 4.2.23 on 2025-09-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_sensor_sleep_time_room_sleep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='sleep_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='wake_time',
            field=models.TimeField(),
        ),
    ]
