# Generated by Django 4.2.23 on 2025-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_room_sleep_time_alter_room_wake_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='device_number',
            field=models.IntegerField(default=0),
        ),
    ]
