# Generated by Django 4.2.23 on 2025-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_room_device_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='device_number',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
