# Generated by Django 4.2.23 on 2025-09-07 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_room_device_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='device_number',
        ),
        migrations.AddField(
            model_name='room',
            name='heat_sensor_id',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='HeatingDevice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main_app.room')),
            ],
        ),
    ]
