# Generated by Django 4.2.23 on 2025-09-07 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_remove_room_device_number_room_heat_sensor_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_temperature',
            field=models.FloatField(blank=True, default=-1),
        ),
    ]
