# Generated by Django 4.2.23 on 2025-09-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_room_current_temperature'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'permissions': [('change_temperature', 'Can change ideal temperature'), ('change_wakesleep', 'Can change Wake and Sleep time of device'), ('assign_device', 'Can assign a device to a room'), ('view_auditlog', 'Can view room audit logs'), ('can_promote_student', 'Can promote a Student/Teacher to a Facilities Staff')]},
        ),
    ]
