# Generated by Django 4.2.23 on 2025-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_room_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_temperature',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
