# Generated by Django 4.2.23 on 2025-09-08 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_room_current_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
