# Generated by Django 4.2.20 on 2025-10-22 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_auditlog_room_alter_auditlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='heatingdevice',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='ideal_temperature',
            field=models.FloatField(default=27),
        ),
        migrations.AlterField(
            model_name='room',
            name='sleep_time',
            field=models.TimeField(default=datetime.time(22, 0)),
        ),
        migrations.AlterField(
            model_name='room',
            name='wake_time',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
    ]
