# Generated by Django 4.2.20 on 2025-10-22 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_heatingdevice_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heatingdevice',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='main_app.room'),
        ),
    ]
