# Generated by Django 4.2.20 on 2025-10-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_alter_heatingdevice_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='current_temperature',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
    ]
